#!/bin/bash

P3=
if [ -f $(which python3.6) ]; then
    P3=3.6
fi

CMD=$1
shift

if [ $CMD = "install" ]; then
    python${P3} -m venv venv
    . ./venv/bin/activate
    pip install --upgrade pip || echo "Please first sudo apt install python${P3}-pip"
    pip install --upgrade setuptools
    pip install --upgrade -r requirements.txt
    exit 0
fi

if [ ! -f "venv/bin/activate" ]; then
    ./run install
fi

. ./venv/bin/activate || exit -1

if [ $CMD = "server" ]; then
    flask run --host=0.0.0.0 --port=5000 "$@"
elif [ $CMD = "local" ]; then
    python local.py "$@"
elif [ $CMD = "lint" ]; then
    mypy *.py app/*.py tests/*.py &&
        flake8 &&
        (yapf -d *.py tests/*.py app/*.py >/dev/null || (echo 'Format not happy, do ./run format!' && exit -1))
elif [ $CMD = "format" ]; then
    yapf -i *.py tests/*.py app/*.py "$@"
elif [ $CMD = "test" ]; then
    ./run lint && python -m pytest -v -q "$@"
else
    "$CMD" "$@"
fi
