### Add seqs
PUT http://localhost:5005/classification_sample?model=dummy_model HTTP/1.1
content-type: application/json

{
    "samples": [
        {
            "seq": "hello world",
            "training_labels" : [{
                "topic": "abc"
            }]
        },
        {
            "seq": "hello world 2",
            "training_labels" : [{
                "topic": "abc2"
            }]
        },
        {
            "seq": "hello world 3"
        }
    ]
}

### Get seqs
GET http://localhost:5005/classification_sample?model=dummy_model&seq=*&limit=3 HTTP/1.1

### Del seqs
DELETE http://localhost:5005/classification_sample?model=dummy_model&seq=hello%20world HTTP/1.1

### Del all
DELETE http://localhost:5005/classification_sample?model=dummy_model&seq=* HTTP/1.1

### Classify
POST http://localhost:5005/classify?model=upr-info-issues HTTP/1.1
content-type: application/json

{
    "samples": [
        {
            "seq": "continue to defend children's rights"
        },
        {
            "seq": "implement measures against enforced disappearance",
            "sharedId": "123"
        }
    ]
}

### Train task
POST http://localhost:5005/task HTTP/1.1
content-type: application/json

{
    "provider": "TrainModel",
    "name": "train-dummy_model",
    "model": "dummy_model",
    "labels": ["elderly", "cow", "pig", "duck"],
    "num_train_steps": 10,
    "train_ratio": 0.4,
    "samples": [
        {
            "seq": "old macdonal had a farm",
            "training_labels": ["elderly"]
        },
        {
            "seq": "old macdonal has a farm",
            "training_labels": ["elderly"]
        },
        {
            "seq": "old macdonal with the farm",
            "training_labels": ["elderly"]
        },
        {
            "seq": "old macdonal had a farm 2",
            "training_labels": ["elderly"]
        },
        {
            "seq": "old macdonal has a farm 2",
            "training_labels": ["elderly"]
        },
        {
            "seq": "old macdonal with the farm 2",
            "training_labels": ["elderly"]
        },
        {
            "seq": "old macdonal had a farm 3",
            "training_labels": ["elderly"]
        },
        {
            "seq": "old macdonal has a farm 3",
            "training_labels": ["elderly"]
        },
        {
            "seq": "old macdonal with the farm 3",
            "training_labels": ["elderly"]
        },
        {
            "seq": "old macdonal had a farm 4",
            "training_labels": ["elderly"]
        },
        {
            "seq": "old macdonal has a farm 4",
            "training_labels": ["elderly"]
        },
        {
            "seq": "old macdonal with the farm 4",
            "training_labels": ["elderly"]
        },
        {
            "seq": "old macdonal had a farm 5",
            "training_labels": ["elderly"]
        },
        {
            "seq": "old macdonal has a farm 5",
            "training_labels": ["elderly"]
        },
        {
            "seq": "old macdonal with the farm 5",
            "training_labels": ["elderly"]
        },
        {
            "seq": "old macdonal had a farm 6",
            "training_labels": ["elderly"]
        },
        {
            "seq": "old macdonal has a farm 6",
            "training_labels": ["elderly"]
        },
        {
            "seq": "old macdonal with the farm 6",
            "training_labels": ["elderly"]
        },
        {
            "seq": "And on his farm he had a cow",
            "training_labels": ["cow"]
        },
        {
            "seq": "With a moo moo here",
            "training_labels": ["cow"]
        },
        {
            "seq": "Here a moo, there a moo",
            "training_labels": ["cow"]
        },
        {
            "seq": "Everywhere a moo moo",
            "training_labels": ["cow"]
        },
        {
            "seq": "And on his farm he had a cow 2",
            "training_labels": ["cow"]
        },
        {
            "seq": "With a moo moo here 2",
            "training_labels": ["cow"]
        },
        {
            "seq": "Here a moo, there a moo 2",
            "training_labels": ["cow"]
        },
        {
            "seq": "Everywhere a moo moo 2",
            "training_labels": ["cow"]
        }
    ]
}

### Train task GET
GET http://localhost:5005/task HTTP/1.1
content-type: application/json

{
    "name": "train-dummy_model"
}


### Get seqs
GET http://localhost:5005/classification_sample?model=upr-info-issues&seq=*&limit=3 HTTP/1.1

### Wait task
POST http://localhost:5005/task HTTP/1.1
content-type: application/json

{
    "provider": "Wait",
    "name": "wait_100",
    "time": 2.0
}

### Wait task GET
GET http://localhost:5005/task HTTP/1.1
content-type: application/json

{
    "name": "wait_100"
}


### Wait task DELETE
DELETE http://localhost:5005/task HTTP/1.1
content-type: application/json

{
    "name": "wait_100"
}

### Model Status
GET http://localhost:5005/models/list HTTP/1.1
content-type: application/json

### Model Status with Filter
GET http://localhost:5005/models/list?filter=upr-info-issues HTTP/1.1
content-type: application/json


### Model Instances
GET http://localhost:5005/models?model=upr-info-issues HTTP/1.1
content-type: application/json

